import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, Type, Schema } from "@google/genai";

// Ensure the API route isn't statically cached
export const dynamic = "force-dynamic";

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

const SYSTEM_INSTRUCTION = `
You are simulating a structured, multi-stage chest X-ray analysis and reporting workflow for a
research prototype. You are not a real diagnostic system and must never claim certainty about a
real patient's condition. Write in a confident, terse clinical register throughout — avoid
AI-ish hedging phrases like "I think" or "it appears that I". Analyze the attached frontal chest
X-ray image and respond ONLY with JSON matching the provided schema.

0. IMAGE VALIDATION: Look at the image first. Is it a medical chest X-ray? If it is a picture of an animal, an apple, a car, a selfie, or any image that is clearly NOT a medical chest X-ray, you MUST set "is_valid_xray": false. If it is a chest X-ray, set "is_valid_xray": true. If false, you can leave the rest of the fields with empty or dummy values.

1. CLASSIFICATION: Assess exactly these 14 findings, using exactly these four statuses:
   "Positive", "Negative", "Uncertain", "Not Mentioned".
   Atelectasis, Cardiomegaly, Consolidation, Edema, Enlarged Cardiomediastinum, Fracture,
   Lung Lesion, Lung Opacity, No Finding, Pleural Effusion, Pleural Other, Pneumonia,
   Pneumothorax, Support Devices.
   Give a confidence 0-1 per label (your own estimate) and a risk_group: RED for Atelectasis,
   Cardiomegaly, Consolidation, Enlarged Cardiomediastinum, Lung Opacity, Pneumonia; otherwise
   YELLOW or GREEN based on your assessment difficulty for this specific image.

2. REPORT: Write Findings and Impression paragraphs in standard radiology-report style — short
   declarative sentences, consistent with the classification above.

3. REGIONS OF INTEREST: For each Positive or Uncertain finding, return a bounding box
   (box_2d: [ymin, xmin, ymax, xmax], normalized 0-1000) over the region best supporting that
   finding. Label these as model-highlighted regions of interest — not Grad-CAM, not a real
   saliency map, an estimate.

4. SIMULATED AGENT TRACE (five stages, generated by you in one pass, written as if five
   specialists contributed):
   - retrieval_context: 1-2 sentences on what typical presentation pattern this resembles,
     explicitly framed as general pattern reasoning, not retrieval from a real report database.
   - draft_report: a simpler first-pass findings/impression draft.
   - refinement_actions: list of {action: ADD|REMOVE|SOFTEN|KEEP, label, reason} showing how the
     draft became the final report, evidence-gated on the classification.
   - vision_check_notes: 1-2 sentences on visual plausibility of the top findings.
   - synthesis_notes: 1 sentence on why the final confidence/review decision was made.

5. UNCERTAINTY: Estimate u_classification and u_generation (0-1 each).
   u_final = 0.6 * u_classification + 0.4 * u_generation.
   status = "FLAGGED_FOR_REVIEW" if u_final >= 0.35, OR any of Consolidation/Edema/
   Pleural Effusion/Pneumothorax is Positive or Uncertain with confidence below 0.6.
   Otherwise status = "AUTOMATED_READY".

6. Include the fixed disclaimer field exactly as given in the schema description, unaltered.

Respond with JSON only, no prose outside the JSON structure.
`;

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    is_valid_xray: {
      type: Type.BOOLEAN,
      description: "True if the image is a Chest X-Ray. False if it is not a medical chest X-ray (e.g. an apple, an animal, a selfie)."
    },
    classification: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          label: { type: Type.STRING },
          status: { type: Type.STRING, enum: ["Positive", "Negative", "Uncertain", "Not Mentioned"] },
          confidence: { type: Type.NUMBER },
          risk_group: { type: Type.STRING, enum: ["RED", "YELLOW", "GREEN"] },
        },
        required: ["label", "status", "confidence", "risk_group"],
      },
    },
    report: {
      type: Type.OBJECT,
      properties: {
        findings: { type: Type.STRING },
        impression: { type: Type.STRING },
      },
      required: ["findings", "impression"],
    },
    regions_of_interest: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          label: { type: Type.STRING },
          box_2d: {
            type: Type.ARRAY,
            items: { type: Type.NUMBER },
            description: "[ymin, xmin, ymax, xmax] normalized 0-1000",
          },
          note: { type: Type.STRING },
        },
        required: ["label", "box_2d", "note"],
      },
    },
    agent_trace: {
      type: Type.OBJECT,
      properties: {
        retrieval_context: { type: Type.STRING },
        draft_report: {
          type: Type.OBJECT,
          properties: {
            findings: { type: Type.STRING },
            impression: { type: Type.STRING },
          },
          required: ["findings", "impression"],
        },
        refinement_actions: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              action: { type: Type.STRING, enum: ["ADD", "REMOVE", "SOFTEN", "KEEP"] },
              label: { type: Type.STRING },
              reason: { type: Type.STRING },
            },
            required: ["action", "label", "reason"],
          },
        },
        vision_check_notes: { type: Type.STRING },
        synthesis_notes: { type: Type.STRING },
      },
      required: [
        "retrieval_context",
        "draft_report",
        "refinement_actions",
        "vision_check_notes",
        "synthesis_notes",
      ],
    },
    uncertainty: {
      type: Type.OBJECT,
      properties: {
        u_classification: { type: Type.NUMBER },
        u_generation: { type: Type.NUMBER },
        u_final: { type: Type.NUMBER },
        status: { type: Type.STRING, enum: ["AUTOMATED_READY", "FLAGGED_FOR_REVIEW"] },
      },
      required: ["u_classification", "u_generation", "u_final", "status"],
    },
    disclaimer: {
      type: Type.STRING,
      description: "This is a dummy prototype demonstrating a proposed thesis workflow's user experience. It uses a general-purpose multimodal AI model (Gemini), not the trained classification/retrieval/generation pipeline described in the underlying thesis, and its outputs are illustrative only. Not a medical device — do not use for real clinical decisions.",
    },
  },
  required: [
    "classification",
    "report",
    "regions_of_interest",
    "agent_trace",
    "uncertainty",
    "disclaimer",
  ],
};

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const imageFile = formData.get("image") as File | null;

    if (!imageFile) {
      return NextResponse.json({ error: "No image provided" }, { status: 400 });
    }

    if (imageFile.size > 10 * 1024 * 1024) {
      return NextResponse.json({ error: "Image size exceeds 10MB limit" }, { status: 400 });
    }

    const mimeType = imageFile.type;
    const validMimeTypes = ["image/jpeg", "image/png", "image/webp"];
    if (!validMimeTypes.includes(mimeType)) {
      return NextResponse.json({ error: "Invalid image format" }, { status: 400 });
    }

    const arrayBuffer = await imageFile.arrayBuffer();
    const base64Data = Buffer.from(arrayBuffer).toString("base64");

    const modelName = process.env.GEMINI_MODEL || "gemini-3.5-flash";

    const response = await ai.models.generateContent({
      model: modelName,
      contents: [
        {
          role: "user",
          parts: [
            { text: SYSTEM_INSTRUCTION },
            {
              inlineData: {
                data: base64Data,
                mimeType: mimeType,
              },
            },
          ],
        },
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        temperature: 0.3,
      },
    });

    if (!response.text) {
      throw new Error("Empty response from Gemini API");
    }

    const parsedData = JSON.parse(response.text);

    // Add server-generated case_id and timestamp
    const case_id = `CXR-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
    const processed_at = new Date().toISOString();

    return NextResponse.json({
      ...parsedData,
      case_id,
      processed_at,
    });
  } catch (error: unknown) {
    console.error("API Error:", error);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: "An error occurred during analysis.", details: errorMessage }, { status: 500 });
  }
}
